# Generated by Django 2.2.10 on 2020-02-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
    ]
